/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tokosembakoberkah.view.Transaksi;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tokosembakoberkah.controller.EntitasController;
import tokosembakoberkah.controller.UserController;
import tokosembakoberkah.model.EntitasModel;
import tokosembakoberkah.model.UserModel;

/**
 *
 * @author Lenovo
 */
public class PilihOpsi extends javax.swing.JDialog {

    /**
     * Creates new form PilihOpsi
     */
    private final EntitasController entitasController;
    private String type;
    private int currentPage = 1;
    private final int rowsPerPage = 10;

    public PilihOpsi(java.awt.Frame parent, boolean modal, String type) {
        super(parent, modal);
        initComponents();
        this.type = type; // Perbaikan: Tambahkan titik koma di akhir baris ini
        entitasController = new EntitasController();
        loadData();
        updatePaginationButtons();
        render();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PilihData = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        page = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        count = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PilihData1 = new javax.swing.JButton();

        PilihData.setText("Pilih Data");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        prevButton.setText("prev");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        nextButton.setText("next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        page.setText("page 0");

        tabel.setBackground(new java.awt.Color(20, 49, 73));
        tabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        tabel.setForeground(new java.awt.Color(255, 255, 255));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "1", "Supplier", "PT Angkas", "Jln Mujair", "0812399900012"},
                {null, "2", "Suppler", "PT MUJUR", "Jln Apui", "0852399901221"},
                {null, null, "", null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "NO", "TYPE", "NAMA", "ALAMAT", "NO TELP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.setFocusable(false);
        tabel.setGridColor(new java.awt.Color(255, 255, 255));
        tabel.setRowHeight(25);
        tabel.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tabel.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabel.setShowGrid(true);
        tabel.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(0).setMinWidth(0);
            tabel.getColumnModel().getColumn(0).setPreferredWidth(0);
            tabel.getColumnModel().getColumn(0).setMaxWidth(0);
            tabel.getColumnModel().getColumn(1).setMinWidth(50);
            tabel.getColumnModel().getColumn(1).setPreferredWidth(50);
            tabel.getColumnModel().getColumn(1).setMaxWidth(50);
        }

        count.setText("Total 2");

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N

        PilihData1.setText("Pilih Data");
        PilihData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihData1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(PilihData1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(page)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prevButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nextButton)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(count)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prevButton)
                    .addComponent(nextButton)
                    .addComponent(page)
                    .addComponent(PilihData1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(count)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void render() {
        int total = entitasController.getCounts();
        count.setText("Jumlah Data : " + total);
    }

    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        model.setRowCount(0);

        // Mendapatkan daftar barang berdasarkan halaman
        List<EntitasModel> List = entitasController.getEntitasByPagew(currentPage, rowsPerPage, type);

        // Tambahkan data barang ke dalam tabel
        int nomorUrut = (currentPage - 1) * rowsPerPage + 1;
        for (EntitasModel list : List) {
            Object[] rowData = {list.getId(), nomorUrut, list.getType(), list.getNama(), list.getAlamat(), list.getNoTelp()};
            model.addRow(rowData);
            nomorUrut++;
        }
    }
    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        // TODO add your handling code here:
        if (currentPage > 1) {
            currentPage--;
            loadData();
            updatePaginationButtons();
        }
    }//GEN-LAST:event_prevButtonActionPerformed

    private void updatePaginationButtons() {
        int totalRows = entitasController.getCounts();
        int totalPages = (int) Math.ceil((double) totalRows / rowsPerPage);
        System.out.println("total Rows: " + totalRows + "Total Page " + totalPages);
        int prev = 1;
        int next = 0;
        page.setText("Total Pages " + totalPages);
        prevButton.setText("Page " + (currentPage - prev));
        nextButton.setText("Page " + (currentPage + next));
        if (currentPage <= 1) {
            prevButton.setEnabled(false);

        } else {
            prevButton.setEnabled(true);
        }

        if (currentPage >= totalPages) {
            nextButton.setEnabled(false);
        } else {
            nextButton.setEnabled(true);
        }
    }
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        int totalRows = entitasController.getCounts();
        int totalPages = (int) Math.ceil((double) totalRows / rowsPerPage);

        if (currentPage < totalPages) {
            currentPage++;
            loadData();
            updatePaginationButtons();
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private BarangMasuk barangMasuk;
    private BarangKeluar barangKeluar;

    public void setTransaksiPanel(BarangMasuk barangMasuk) {
        this.barangMasuk = barangMasuk;
    }

    public void setTransaksiPanelk(BarangKeluar barangKeluar) {
        this.barangKeluar = barangKeluar;
    }
    private void PilihData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihData1ActionPerformed
        // TODO add your handling code here:
        pilihData();
    }//GEN-LAST:event_PilihData1ActionPerformed
    private void pilihData() {
        int selectedRow = tabel.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        if (selectedRow != -1) {
            // Ambil data yang ingin dikirim
            int id = (int) model.getValueAt(selectedRow, 0);
            String nama = (String) model.getValueAt(selectedRow, 3);
            // Kirim data ke TransaksiPanel
            if ("Supplier".equals(type)) {
                barangMasuk.setData(nama, id);
            } else {
                barangKeluar.setData(nama, id);
            }
            dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris data dulu.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihOpsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihOpsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihOpsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihOpsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PilihOpsi dialog = new PilihOpsi(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PilihData;
    private javax.swing.JButton PilihData1;
    private javax.swing.JLabel count;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel page;
    private javax.swing.JButton prevButton;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
