/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tokosembakoberkah.view;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.SwingUtilities;
import tokosembakoberkah.MainFrame;

/**
 *
 * @author Lenovo
 */
public class Navigation extends javax.swing.JPanel {

    /**
     * Creates new form Navigation
     */
    private JButton activeButton; // Tombol aktif saat ini
    public Navigation() {
        initComponents();
        activeButton = dahsboard; // Menginisialisasi tombol aktif
        setActiveButton(dahsboard); // Mengatur warna latar belakang awal
    }
    private void setActiveButton(JButton button) {
        // Mengubah warna latar belakang tombol aktif sebelumnya (jika ada)
        if (activeButton != null) {
            activeButton.setBackground(Color.darkGray);
        }

        // Mengatur warna latar belakang tombol yang baru menjadi berbeda
        button.setBackground(Color.blue);

        // Mengatur tombol yang baru sebagai tombol aktif
        activeButton = button;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dahsboard = new javax.swing.JButton();
        Transaksi = new javax.swing.JButton();
        Barang = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        dahsboard.setText("Dashboard");
        dahsboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dahsboardActionPerformed(evt);
            }
        });

        Transaksi.setText("Transaksi");
        Transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiActionPerformed(evt);
            }
        });

        Barang.setText("Barang");
        Barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Barang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dahsboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(dahsboard)
                .addGap(28, 28, 28)
                .addComponent(Barang)
                .addGap(18, 18, 18)
                .addComponent(Transaksi)
                .addContainerGap(407, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarangActionPerformed
        // TODO add your handling code here:
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        mainFrame.changeContentPanel("barang");

        setActiveButton(Barang); // Mengatur tombol dahsboard sebagai tombol aktif
    }//GEN-LAST:event_BarangActionPerformed

    private void TransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiActionPerformed
        // TODO add your handling code here:
               MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        mainFrame.changeContentPanel("transaksi");

        setActiveButton(Transaksi); // Mengatur tombol dahsboard sebagai tombol aktif
    }//GEN-LAST:event_TransaksiActionPerformed

    private void dahsboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dahsboardActionPerformed
        // TODO add your handling code here:
             MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        mainFrame.changeContentPanel("dashboard");

        setActiveButton(dahsboard); // Mengatur tombol dahsboard sebagai tombol aktif
    }//GEN-LAST:event_dahsboardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Barang;
    private javax.swing.JButton Transaksi;
    private javax.swing.JButton dahsboard;
    // End of variables declaration//GEN-END:variables
}
