/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tokosembakoberkah.view.Navigation;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.SwingUtilities;
import tokosembakoberkah.MainFrame;

/**
 *
 * @author Lenovo
 */
public class Navigation extends javax.swing.JPanel {

    /**
     * Creates new form Navigation
     */
    private JButton activeButton; // Tombol aktif saat ini
    public Navigation() {
        initComponents();
        activeButton = dahsboard; // Menginisialisasi tombol aktif tes
        setActiveButton(dahsboard); // Mengatur warna latar belakang awal
    }
    private void setActiveButton(JButton button) {
        // Mengubah warna latar belakang tombol aktif sebelumnya (jika ada)
        if (activeButton != null) {
            activeButton.setBackground(new Color(20,49,73));
            activeButton.setForeground(Color.WHITE);
        }

        // Mengatur warna latar belakang tombol yang baru menjadi berbeda
       button.setBackground(new Color(255, 153, 51));
 button.setForeground(Color.WHITE);
        // Mengatur tombol yang baru sebagai tombol aktif
        activeButton = button;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dahsboard = new javax.swing.JButton();
        Transaksi = new javax.swing.JButton();
        Barang = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        SP = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setToolTipText("");

        dahsboard.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        dahsboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/dashboard.png"))); // NOI18N
        dahsboard.setText("  Dashboard");
        dahsboard.setFocusPainted(false);
        dahsboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dahsboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dahsboardActionPerformed(evt);
            }
        });

        Transaksi.setBackground(new java.awt.Color(20, 49, 73));
        Transaksi.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Transaksi.setForeground(java.awt.Color.white);
        Transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/transaksi.png"))); // NOI18N
        Transaksi.setText("  Transaksi");
        Transaksi.setFocusPainted(false);
        Transaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiActionPerformed(evt);
            }
        });

        Barang.setBackground(new java.awt.Color(20, 49, 73));
        Barang.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Barang.setForeground(new java.awt.Color(255, 255, 255));
        Barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/barang.png"))); // NOI18N
        Barang.setText("  Barang");
        Barang.setFocusPainted(false);
        Barang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarangActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(246, 246, 246));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/inventory.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PT TOKO SEMBAKO BERKAH");
        jLabel1.setFocusable(false);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        SP.setBackground(new java.awt.Color(20, 49, 73));
        SP.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        SP.setForeground(java.awt.Color.white);
        SP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/sp.png"))); // NOI18N
        SP.setText("  Supplier & pelanggan ");
        SP.setFocusPainted(false);
        SP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dahsboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dahsboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Barang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarangActionPerformed
        // TODO add your handling code here:
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        mainFrame.changeContentPanel("barang");

        setActiveButton(Barang); // Mengatur tombol dahsboard sebagai tombol aktif
    }//GEN-LAST:event_BarangActionPerformed

    private void TransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiActionPerformed
        // TODO add your handling code here:
               MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        mainFrame.changeContentPanel("transaksi");

        setActiveButton(Transaksi); // Mengatur tombol dahsboard sebagai tombol aktif
    }//GEN-LAST:event_TransaksiActionPerformed

    private void dahsboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dahsboardActionPerformed
        // TODO add your handling code here:
             MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        mainFrame.changeContentPanel("dashboard");

        setActiveButton(dahsboard); // Mengatur tombol dahsboard sebagai tombol aktif
    }//GEN-LAST:event_dahsboardActionPerformed

    private void SPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPActionPerformed
        // TODO add your handling code here:
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        mainFrame.changeContentPanel("sp");

        setActiveButton(SP); // Mengatur tombol dahsboard sebagai tombol aktif
    }//GEN-LAST:event_SPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Barang;
    private javax.swing.JButton SP;
    private javax.swing.JButton Transaksi;
    private javax.swing.JButton dahsboard;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
